apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: clusters-service-viewer-role
    namespace: {{ .Values.config.capi.clusters.namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: clusters-service-viewer-role
subjects:
    - kind: ServiceAccount
      name: {{ include "mccp.serviceAccountName" . }}
      namespace: {{ .Release.Namespace | quote }}