# permissions for end users to view WeGO applications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-viewer-role
rules:
  - apiGroups:
      - wego.weave.works
    resources:
      - apps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - wego.weave.works
    resources:
      - apps/status
    verbs:
      - get