apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: capi-server
  template:
    metadata:
      labels:
        name: capi-server
    spec:
      imagePullSecrets:
      - name: docker-io-pull-secret
      containers:
      - name: capi-server
        image: weaveworks/capi-server
        imagePullPolicy: IfNotPresent
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TEMPLATE_CONFIGMAP_NAME
            value: capi-templates
        ports:
        - containerPort: 8000
