---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: gitopstemplates.clustertemplates.weave.works
spec:
  group: clustertemplates.weave.works
  names:
    kind: GitOpsTemplate
    listKind: GitOpsTemplateList
    plural: gitopstemplates
    singular: gitopstemplate
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: GitOpsTemplate is the Schema for the GitOpsTemplate API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TemplateSpec defines the base template spec needs for CAPI
              or Terraform Templates.
            properties:
              description:
                description: Description is used to describe the purpose of this template
                  for user information.
                type: string
              params:
                description: Params is the set of parameters that are used in this
                  template with descriptions.
                items:
                  description: TemplateParam is a parameter that can be templated
                    into a struct.
                  properties:
                    description:
                      type: string
                    name:
                      type: string
                    options:
                      items:
                        type: string
                      type: array
                    required:
                      type: boolean
                  required:
                  - name
                  type: object
                type: array
              renderType:
                default: envsubst
                description: RenderType specifies which templating language to use
                  to render templates. Defaults to 'envsubst', valid values are ('envsubst',
                  'templating').
                enum:
                - envsubst
                - templating
                type: string
              resourcetemplates:
                description: ResourceTemplates are a set of templates for resources
                  that are generated from this Template.
                items:
                  description: ResourceTemplate describes a resource to create.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                type: array
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
