apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: capitemplates.capi.weave.works
spec:
  group: capi.weave.works
  names:
    kind: CAPITemplate
    listKind: CAPITemplateList
    plural: capitemplates
    singular: capitemplate
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: CAPITemplate is the Schema for the capitemplates API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TemplateSpec defines the base template spec needs for CAPI
              or Terraform Templates.
            properties:
              charts:
                description: Charts is the set of charts that are used in this template.
                properties:
                  helmRepositoryTemplate:
                    description: Template for the HelmRepository. Shortcut to template.content.spec.chart.spec.helmRepositoryTemplate
                    properties:
                      path:
                        type: string
                    type: object
                  items:
                    items:
                      description: Chart is the set of values that control the default
                        and required values of a chart/profile in a template.
                      properties:
                        chart:
                          description: Name of the chart/profile in the Helm repository.
                            Shortcut to template.content.spec.chart.spec.chart
                          type: string
                        editable:
                          description: If true you can change the values and version
                            of the chart/profile
                          type: boolean
                        layer:
                          description: Layer, overrides the default layer provided
                            in the Helm Repository
                          type: string
                        required:
                          description: If true the chart/profile will always be installed
                          type: boolean
                        sourceRef:
                          description: SourceRef is the name/namespace reference to
                            the HelmRepository. No other source types are currently
                            supported. The HelmRepository must be present on the rendering
                            cluster. The full referenced HelmRepository resource will
                            be included in the template output.
                          properties:
                            apiVersion:
                              description: API version of the referent.
                              type: string
                            fieldPath:
                              description: 'If referring to a piece of an object instead
                                of an entire object, this string should contain a
                                valid JSON/Go field access statement, such as desiredState.manifest.containers[2].
                                For example, if the object reference is to a container
                                within a pod, this would take on a value like: "spec.containers{name}"
                                (where "name" refers to the name of the container
                                that triggered the event) or if no container name
                                is specified "spec.containers[2]" (container with
                                index 2 in this pod). This syntax is chosen only to
                                have some well-defined way of referencing a part of
                                an object. TODO: this design is not final and this
                                field is subject to change in the future.'
                              type: string
                            kind:
                              description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                              type: string
                            name:
                              description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                              type: string
                            namespace:
                              description: 'Namespace of the referent. More info:
                                https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                              type: string
                            resourceVersion:
                              description: 'Specific resourceVersion to which this
                                reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency'
                              type: string
                            uid:
                              description: 'UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids'
                              type: string
                          type: object
                          x-kubernetes-map-type: atomic
                        targetNamespace:
                          description: Shortcut to template.content.spec.targetNamespace
                          type: string
                        template:
                          description: Template for the HelmRelease, merged with the
                            default template.
                          properties:
                            content:
                              description: Content of the template
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
                            path:
                              description: Path of the template
                              type: string
                          type: object
                        values:
                          description: Shortcut to template.content.spec.values
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                        version:
                          description: Default version to select. Shortcut to template.content.spec.chart.spec.version
                          type: string
                      required:
                      - chart
                      type: object
                    type: array
                type: object
              description:
                description: Description is used to describe the purpose of this template
                  for user information.
                type: string
              params:
                description: Params is the set of parameters that are used in this
                  template with descriptions.
                items:
                  description: TemplateParam is a parameter that can be templated
                    into a struct.
                  properties:
                    default:
                      description: Default specifies the default value for the parameter
                      type: string
                    description:
                      type: string
                    name:
                      type: string
                    options:
                      items:
                        type: string
                      type: array
                    required:
                      default: true
                      description: Required indicates whether the param must contain
                        a non-empty value
                      type: boolean
                  required:
                  - name
                  type: object
                type: array
              renderType:
                default: envsubst
                description: RenderType specifies which templating language to use
                  to render templates. Defaults to 'envsubst', valid values are ('envsubst',
                  'templating').
                enum:
                - envsubst
                - templating
                type: string
              resourcetemplates:
                description: ResourceTemplates are a set of templates for resources
                  that are generated from this Template.
                items:
                  description: ResourceTemplateContent describes a resource to create.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                type: array
            type: object
        type: object
    served: true
    storage: false
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        description: CAPITemplate is the Schema for the capitemplates API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TemplateSpec defines the base template spec needs for CAPI
              or Terraform Templates.
            properties:
              charts:
                description: Charts is the set of charts that are used in this template.
                properties:
                  helmRepositoryTemplate:
                    description: Template for the HelmRepository. Shortcut to template.content.spec.chart.spec.helmRepositoryTemplate
                    properties:
                      path:
                        type: string
                    type: object
                  items:
                    items:
                      description: Chart is the set of values that control the default
                        and required values of a chart/profile in a template.
                      properties:
                        chart:
                          description: Name of the chart/profile in the Helm repository.
                            Shortcut to template.content.spec.chart.spec.chart
                          type: string
                        editable:
                          description: If true you can change the values and version
                            of the chart/profile
                          type: boolean
                        layer:
                          description: Layer, overrides the default layer provided
                            in the Helm Repository
                          type: string
                        required:
                          description: If true the chart/profile will always be installed
                          type: boolean
                        sourceRef:
                          description: SourceRef is the name/namespace reference to
                            the HelmRepository. No other source types are currently
                            supported. The HelmRepository must be present on the rendering
                            cluster. The full referenced HelmRepository resource will
                            be included in the template output.
                          properties:
                            apiVersion:
                              description: API version of the referent.
                              type: string
                            fieldPath:
                              description: 'If referring to a piece of an object instead
                                of an entire object, this string should contain a
                                valid JSON/Go field access statement, such as desiredState.manifest.containers[2].
                                For example, if the object reference is to a container
                                within a pod, this would take on a value like: "spec.containers{name}"
                                (where "name" refers to the name of the container
                                that triggered the event) or if no container name
                                is specified "spec.containers[2]" (container with
                                index 2 in this pod). This syntax is chosen only to
                                have some well-defined way of referencing a part of
                                an object. TODO: this design is not final and this
                                field is subject to change in the future.'
                              type: string
                            kind:
                              description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                              type: string
                            name:
                              description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                              type: string
                            namespace:
                              description: 'Namespace of the referent. More info:
                                https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                              type: string
                            resourceVersion:
                              description: 'Specific resourceVersion to which this
                                reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency'
                              type: string
                            uid:
                              description: 'UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids'
                              type: string
                          type: object
                          x-kubernetes-map-type: atomic
                        targetNamespace:
                          description: Shortcut to template.content.spec.targetNamespace
                          type: string
                        template:
                          description: Template for the HelmRelease, merged with the
                            default template.
                          properties:
                            content:
                              description: Content of the template
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
                            path:
                              description: Path of the template
                              type: string
                          type: object
                        values:
                          description: Shortcut to template.content.spec.values
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                        version:
                          description: Default version to select. Shortcut to template.content.spec.chart.spec.version
                          type: string
                      required:
                      - chart
                      type: object
                    type: array
                type: object
              description:
                description: Description is used to describe the purpose of this template
                  for user information.
                type: string
              params:
                description: Params is the set of parameters that are used in this
                  template with descriptions.
                items:
                  description: TemplateParam is a parameter that can be templated
                    into a struct.
                  properties:
                    default:
                      description: Default specifies the default value for the parameter
                      type: string
                    description:
                      type: string
                    name:
                      type: string
                    options:
                      items:
                        type: string
                      type: array
                    required:
                      default: true
                      description: Required indicates whether the param must contain
                        a non-empty value
                      type: boolean
                  required:
                  - name
                  type: object
                type: array
              renderType:
                default: envsubst
                description: RenderType specifies which templating language to use
                  to render templates. Defaults to 'envsubst', valid values are ('envsubst',
                  'templating').
                enum:
                - envsubst
                - templating
                type: string
              resourcetemplates:
                description: ResourceTemplates are a set of templates for resources
                  that are generated from this Template.
                items:
                  description: ResourceTemplate holds a list of resources that can
                    be created from a template and the path to write them to.
                  properties:
                    content:
                      items:
                        description: ResourceTemplateContent describes a resource
                          to create.
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      type: array
                    path:
                      type: string
                    raw:
                      description: Raw is the content of the resource template in
                        a string format. It supports comments in the template file.
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
