# https://github.com/helm/helm/issues/3053#issuecomment-782837107
apiVersion: v1
kind: Secret
metadata:
  name: nats-env-vars-secret
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
{{- $previous := lookup "v1" "Secret" .Release.Namespace "nats-env-vars-secret" }}
data:
  {{- if $previous }}
  NATS_AUTH_TOKEN: {{ $previous.data.NATS_AUTH_TOKEN }}
  {{- else if .Values.NATS_AUTH_TOKEN }}
  NATS_AUTH_TOKEN: {{ .Values.NATS_AUTH_TOKEN | b64enc | quote }}
  {{- else }}
  NATS_AUTH_TOKEN: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
